export const CREATE_BOOKING_REQUEST = "CREATE_BOOKING_REQUEST";
export const CREATE_BOOKING_SUCCESS = "CREATE_BOOKING_SUCCESS";
export const CREATE_BOOKING_FAIL = "CREATE_BOOKING_FAIL";

export const MY_BOOKINGS_REQUEST = "MY_BOOKINGS_REQUEST";
export const MY_BOOKINGS_SUCCESS = "MY_BOOKINGS_SUCCESS";
export const MY_BOOKINGS_FAIL = "MY_BOOKINGS_FAIL";

export const ALL_BOOKINGS_REQUEST = "ALL_BOOKINGS_REQUEST";
export const ALL_BOOKINGS_SUCCESS = "ALL_BOOKINGS_SUCCESS";
export const ALL_BOOKINGS_FAIL = "ALL_BOOKINGS_FAIL";

export const DELETE_BOOKING_REQUEST = "DELETE_BOOKING_REQUEST";
export const DELETE_BOOKING_SUCCESS = "DELETE_BOOKING_SUCCESS";
export const DELETE_BOOKING_RESET = "DELETE_BOOKING_RESET";
export const DELETE_BOOKING_FAIL = "DELETE_BOOKING_FAIL";

export const BOOKING_DETAILS_REQUEST = "BOOKING_DETAILS_REQUEST";
export const BOOKING_DETAILS_SUCCESS = "BOOKING_DETAILS_SUCCESS";
export const BOOKING_DETAILS_FAIL = "BOOKING_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
